# @package _global_.model
type: dilated_res           # â† maps to DilatedResNet

init_dim: 64                # channels after first conv
depth: 6                    # number of residual blocks
dropout_rate: 0.2
